s1 = input("nhap chuoi s1 : ")
s2 = (input("nhap chuoi s2 : "))
s3 = (input("nhap chuoi s3 : "))
print("chieu dai chuoi s1", len(s1))
print("chieu dai chuoi s2", len(s2))
print("chieu dai chuoi s3", len(s3))
print("chuoi s4", s1[2:5])
print("chuoi s2 lap lai hai han", s2*2)